services:
  api:
    build: .
    command: ./go-api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=godb
      - POSTGRES_USER=go
      - POSTGRES_PASSWORD=go
      - POSTGRES_HOST=db
      - PORT=8000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: godb
      POSTGRES_USER: go
      POSTGRES_PASSWORD: go
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U go -d godb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

